### ISSUE TITLE
Bufferlist doesn't open after opening it a couple of times, opening more buffers, jumping around, ...

### ISSUE THREAD

**Issue by loissascha** [EL-MASTOR/bufferlist.nvim#3] opened 2024-10-18 14:32 UTC
After opening a couple of buffers (with neo-tree in case this matters) and using bufferlist a couple of times, jumping around between buffers and opening new buffers, I pretty quickly reach a point where I keep getting this erorr message whenever I try to open it:
![image](https://github.com/user-attachments/assets/f32e82e6-8276-4648-809c-e5d5b4216955)

I'm not able to reproduce it reliably. Sometimes it happens after opening 2 buffers and using bufferlist like 3 times, sometimes after opening 5 buffers and using it 7 times. But it happens pretty quickly.

**Comment by aldarg** [comment] 2024-10-18 14:40
Same error here, but I wasn't able open the buffer list even a single time. Tried to use it in rust project full of errors and warnings.

**Comment by loissascha** [comment] 2024-10-18 14:47
@aldarg did you change the keybinds? Because if you did you gotta change both of them to the same one, otherwise it won't show up
![image](https://github.com/user-attachments/assets/95c10690-c1d0-4236-8ff9-224ed59ce029)

**Comment by aldarg** [comment] 2024-10-18 15:24
No, just copied LazyVim setup from README:
![image](https://github.com/user-attachments/assets/42b7c8f4-581b-41b5-ae22-1f202fa89195)

I'm no expert in lua, but callstack in error stops at iterating through diagnostics. So it seems that keybind is working. I mean it calls the plugin functions.

**Comment by EL-MASTOR** [comment] 2024-10-18 16:47
> After opening a couple of buffers (with neo-tree in case this matters) and using bufferlist a couple of times, jumping around between buffers and opening new buffers, I pretty quickly reach a point where I keep getting this erorr message whenever I try to open it: ![image](https://private-user-images.githubusercontent.com/69523055/377904743-f32e82e6-8276-4648-809c-e5d5b4216955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjc5MjYsIm5iZiI6MTcyOTI2NzYyNiwicGF0aCI6Ii82OTUyMzA1NS8zNzc5MDQ3NDMtZjMyZTgyZTYtODI3Ni00NjQ4LTgwOWMtZTVkNWI0MjE2OTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxMmU0MjZmMWZiMGExNGI3ODExNTI3OGY2NTYyYzJjYWQ2M2Q5NjIxOWFiNTVjMGIxZmZhYTZkZDcwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OxFius3TDuN313K3AqQQ0bQu5PbWsKJ4akPkKdEMW6k)
> 
> I'm not able to reproduce it reliably. Sometimes it happens after opening 2 buffers and using bufferlist like 3 times, sometimes after opening 5 buffers and using it 7 times. But it happens pretty quickly.

I think the error is caused by attempting to index the value returned by `sign_getdefined`.
Could you please run those lines and share their results :

`:lua =vim.fn.sign_getdefined('DiagnosticSignError')`
`:lua =vim.fn.sign_getdefined('DiagnosticSignWarn')`
`:lua =vim.fn.sign_getdefined('DiagnosticSignInfo')`
`:lua =vim.fn.sign_getdefined('DiagnosticSignHint')`

They should output something like this:
`{ {                                        name = "DiagnosticSignError",          text = " ",                           texthl = "DiagnosticSignError"
  } }`

**Comment by aldarg** [comment] 2024-10-18 17:39
Ok, I did some debugging on file with some warnings and errors.
vim.diagnostic.count(0) shows:
```
{
  [2] = 4,
  [4] = 4
}
```
So, 4 warnings and 4 hints. It's true :)

But when I use :sign list (alternative to sign_getdefined) I see all other kinds of signs:
```
sign precognition_gutter_gg text=gg texthl=PrecognitionHighlight
sign todo-sign-NOTE text=  texthl=TodoSignNOTE
sign todo-sign-HACK text=  texthl=TodoSignHACK
sign todo-sign-PERF text=  texthl=TodoSignPERF
sign todo-sign-TODO text=  texthl=TodoSignTODO
sign todo-sign-WARN text=  texthl=TodoSignWARN
sign todo-sign-FIX text=  texthl=TodoSignFIX
sign todo-sign-TEST text=⏲  texthl=TodoSignTEST
sign precognition_gutter_PrevParagraph text={  texthl=PrecognitionHighlight
sign precognition_gutter_NextParagraph text=}  texthl=PrecognitionHighlight
sign precognition_gutter_G text=G  texthl=PrecognitionHighlight
sign neotest_running text=  texthl=NeotestRunning
sign neotest_passed text=  texthl=NeotestPassed
sign neotest_skipped text=  texthl=NeotestSkipped
sign neotest_failed text=  texthl=NeotestFailed
```
When the code tries to filter this list by "DiagnosticSignWarn" key, it gets an empty list, then takes first element, which results in null.
Again, I'm no expert in lua. Actually, I've never ever touched it. But from what I see this is the reason of error.

**Comment by EL-MASTOR** [comment] 2024-10-18 18:44
> After opening a couple of buffers (with neo-tree in case this matters) and using bufferlist a couple of times, jumping around between buffers and opening new buffers, I pretty quickly reach a point where I keep getting this erorr message whenever I try to open it: ![image](https://private-user-images.githubusercontent.com/69523055/377904743-f32e82e6-8276-4648-809c-e5d5b4216955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzY5NzUsIm5iZiI6MTcyOTI3NjY3NSwicGF0aCI6Ii82OTUyMzA1NS8zNzc5MDQ3NDMtZjMyZTgyZTYtODI3Ni00NjQ4LTgwOWMtZTVkNWI0MjE2OTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE4Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGRmNjdhYTY2NTc1ZjU5ZDgxYTBjNjBkOGY1NjYxMWQyOGI2MTgwYzVmMjk3ZWRkZjI1MWRmNjZiNGUwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E_9mpZxlDMZ3aJ_GzfO6HUF0sXR0uDSmY37JaJ71b2A)
> 
> I'm not able to reproduce it reliably. Sometimes it happens after opening 2 buffers and using bufferlist like 3 times, sometimes after opening 5 buffers and using it 7 times. But it happens pretty quickly.

I updated the diagnostics function so that it shows the icons defined by the user if they have, otherwise it falls back to the hard coded icons. It should be fixed now, please update and try again. If you get more errors feel free to  report them.
If it's solved please close this issue.

**Comment by EL-MASTOR** [comment] 2024-10-18 18:51
> After opening a couple of buffers (with neo-tree in case this matters) and using bufferlist a couple of times, jumping around between buffers and opening new buffers, I pretty quickly reach a point where I keep getting this erorr message whenever I try to open it: ![image](https://private-user-images.githubusercontent.com/69523055/377904743-f32e82e6-8276-4648-809c-e5d5b4216955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzc3NTksIm5iZiI6MTcyOTI3NzQ1OSwicGF0aCI6Ii82OTUyMzA1NS8zNzc5MDQ3NDMtZjMyZTgyZTYtODI3Ni00NjQ4LTgwOWMtZTVkNWI0MjE2OTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE4NTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjNkYzA4YmMwNTlmZjMyOTM3YjU2ODIzNTM3ZjJjZmY5YTk4MGEzNTBkN2M2NmQzZDJkMzcxZmIyODFkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4UAqIayWoFtvjLnnwUD4yFk5AHclEqwc7b4xZ88jLOU)
> 
> I'm not able to reproduce it reliably. Sometimes it happens after opening 2 buffers and using bufferlist like 3 times, sometimes after opening 5 buffers and using it 7 times. But it happens pretty quickly.

I updated the diagnostics function so that it shows the icons defined by the user if they have, otherwise it falls back to the hard coded icons. It should be fixed now, please update and try again. If you get more errors feel free to  report them.

**Closed by EL-MASTOR** 2024-10-18 18:51 UTC
